name: Nx CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: '[1/8] Checkout repository'
        uses: actions/checkout@v3

      - name: '[2/8] Install Node.js v20'
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: '[3/8] Install dependencies'
        run: npm ci

      - name: '[4/8] Cache Nx'
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: '[5/8] Check types'
        run: npx tsc --noEmit

      - name: '[6/8] Lint'
        run: npx nx affected --target=lint --parallel=3

      - name: '[7/8] Unit tests'
        run: npx nx affected --target=test --parallel=3

      - name: '[8/8] Build'
        run: npx nx affected --target=build --parallel=3
