name: Nx CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: ai-agent
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ai-agent

    steps:
      - name: '[1/10] Checkout repository'
        uses: actions/checkout@v3

      - name: '[2/10] Install Node.js v22'
        uses: actions/setup-node@v3
        with:
          node-version: 22.16.0

      - name: '[3/10] Install dependencies'
        run: npm ci

      - name: '[4/10] Generate Prisma client'
        run: npx nx run backend:db-generate

      - name: '[5/10] Apply migrations'
        run: npx nx run backend:db-migrate

      - name: '[6/10] Cache Nx'
        uses: actions/cache@v3
        with:
          path: node_modules/.cache/nx
          key: ${{ runner.os }}-nx-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nx-

      - name: '[7/10] Check types'
        run: npx tsc --noEmit

      - name: '[8/10] Lint'
        run: npx nx affected --target=lint --parallel=3

      - name: '[9/10] Unit tests'
        run: npx nx affected --target=test --parallel=3

      - name: '[10/10] Build with Docker'
        run: |
          cd apps/backend
          docker build -t ai-agent-backend:latest -f Dockerfile ../../
          echo "✅ Docker build successful!"
